Traceback (most recent call last):
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
px.imshow(V_k, color_continuous_scale='Turbo',origin="upper", aspect='equal')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [43mpx[49m[38;5;241;43m.[39;49m[43mimshow[49m[43m([49m[43mV_k[49m[43m,[49m[43m [49m[43mcolor_continuous_scale[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mTurbo[39;49m[38;5;124;43m'[39;49m[43m,[49m[43morigin[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mupper[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43maspect[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mequal[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/plotly/express/_imshow.py:354[0m, in [0;36mimshow[0;34m(img, zmin, zmax, origin, labels, x, y, animation_frame, facet_col, facet_col_wrap, facet_col_spacing, facet_row_spacing, color_continuous_scale, color_continuous_midpoint, range_color, title, template, width, height, aspect, contrast_rescaling, binary_string, binary_backend, binary_compression_level, binary_format, text_auto)[0m
[1;32m    351[0m     binary_string [38;5;241m=[39m img[38;5;241m.[39mndim [38;5;241m>[39m[38;5;241m=[39m ([38;5;241m3[39m [38;5;241m+[39m slice_dimensions) [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m is_dataframe
[1;32m    353[0m [38;5;66;03m# Cast bools to uint8 (also one byte)[39;00m
[0;32m--> 354[0m [38;5;28;01mif[39;00m img[38;5;241m.[39mdtype [38;5;241m==[39m [43mnp[49m[38;5;241;43m.[39;49m[43mbool[49m:
[1;32m    355[0m     img [38;5;241m=[39m [38;5;241m255[39m [38;5;241m*[39m img[38;5;241m.[39mastype(np[38;5;241m.[39muint8)
[1;32m    357[0m [38;5;28;01mif[39;00m range_color [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/share/miniconda/envs/gtbook/lib/python3.8/site-packages/numpy/__init__.py:284[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    281[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtesting[39;00m [38;5;28;01mimport[39;00m Tester
[1;32m    282[0m     [38;5;28;01mreturn[39;00m Tester
[0;32m--> 284[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{!r}[39;00m[38;5;124m has no attribute [39m[38;5;124m"[39m
[1;32m    285[0m                      [38;5;124m"[39m[38;5;132;01m{!r}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;18m__name__[39m, attr))

[0;31mAttributeError[0m: module 'numpy' has no attribute 'bool'
AttributeError: module 'numpy' has no attribute 'bool'

